Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20230215.0.0"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Ubuntu_22.04"
    vb.memory = "1024"
    vb.cpus = "2"
  end
end
